#get all employee details
GET http://localhost:3000/employee

#get all admin details

GET http://localhost:3000/admin

#get all superadmin details


GET http://localhost:3000/superadmin

#Create a Employee

POST  http://localhost:3000/employee
Content-Type: application/json

{
    "name": "Varun",
    "age": 22,
    "email": "varun@gmail.com",
    "password": "password@1234",
    "mobile": "9876567890",
    "gdo": "GDO3",
    "skills": "(c,java)"
}

#Create a Admin

POST  http://localhost:3000/admin
Content-Type: application/json

{
    "name": "Siva",
    "age": 20,
    "email": "siva@gmail.com",
    "password": "password@1234",
    "mobile": "9876567890",
    "gdo": "GDO3",
    "skills": "(C++,Perl)"
}

#create a SuperAdmin

POST  http://localhost:3000/superadmin
Content-Type: application/json

{
    "name": "Sravani",
    "age": 20,
    "email": "sravani@gmail.com",
    "password": "password@1234",
    "mobile": "9876567890",
    "gdo": "All",
    "skills": "(Reactjs,java)"
}

